# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppEmpresas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppEmpresas
  pod 'Moya'
  pod 'KeychainSwift'

  target 'AppEmpresasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppEmpresasUITests' do
    # Pods for testing
  end

end
